In [1]:
# Count distance to previous Zero. 
# Count the difference of the distance from the previous Zero or the start of the Series whichever is closer. 
import pandas as pd
import numpy as np

# Define a function to count to the previous zero.

def count_to_zero(df):
    list1=[]
    valuex=0
    for x,y in df.iterrows():
        if y['X'] == 0:
            valuex=x + 1        # If Value is zero, save position+1 to find the relative position of the next value. 
            list1.append(0)
        else:
            newval=[(x + 1 - valuex)] # If the value is not zero, find the difference from the previous zero. 
            list1+=newval
    df['Y']=list1
    return df

# Test with the dataframe in the question.
df1=pd.DataFrame({'X':[7,2,0,1,2,3,4,0,3,4]})
print('Result Dataframe is below:')
print(count_to_zero(df1))

Result Dataframe is below:
   X  Y
0  7  1
1  2  2
2  0  0
3  1  1
4  2  2
5  3  3
6  4  4
7  0  0
8  3  1
9  4  2

In [2]:
# Test the count to zero function with more dataframes
df2=pd.DataFrame({'X':[0,4,5,0,9,0,7,8,10,0]})
print(count_to_zero(df2))

df3=pd.DataFrame({'X':[4,4,5,0,0,0,7,8,10,0]})
print(count_to_zero(df3))

df4=pd.DataFrame({'X':[4,4,5,1,2,3,7,8,10,0]})
print(count_to_zero(df4))

    X  Y
0   0  0
1   4  1
2   5  2
3   0  0
4   9  1
5   0  0
6   7  1
7   8  2
8  10  3
9   0  0
    X  Y
0   4  1
1   4  2
2   5  3
3   0  0
4   0  0
5   0  0
6   7  1
7   8  2
8  10  3
9   0  0
    X  Y
0   4  1
1   4  2
2   5  3
3   1  4
4   2  5
5   3  6
6   7  7
7   8  8
8  10  9
9   0  0

In [3]:
# Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers
# Create a DatetimeIndex with the Business days of 2015
import datetime as dt
dtindx=pd.DatetimeIndex(start='2015-01-01',end='2015-12-31', freq='B')
print('DatatimeIndex is: ')
print(dtindx)

# Index a series of random numbers using the above datetimeindex.
s=pd.Series(np.random.randn(len(dtindx)), index=dtindx)
print('Series of Random Numbers:')
print(s)

DatatimeIndex is:
DatetimeIndex(['2015-01-01', '2015-01-02', '2015-01-05', '2015-01-06',
               '2015-01-07', '2015-01-08', '2015-01-09', '2015-01-12',
               '2015-01-13', '2015-01-14',
               ...
               '2015-12-18', '2015-12-21', '2015-12-22', '2015-12-23',
               '2015-12-24', '2015-12-25', '2015-12-28', '2015-12-29',
               '2015-12-30', '2015-12-31'],
              dtype='datetime64[ns]', length=261, freq='B')
Series of Random Numbers:
2015-01-01    0.877428
2015-01-02   -0.667328
2015-01-05    0.951652
2015-01-06    0.425459
2015-01-07    0.574672
2015-01-08    0.252167
2015-01-09    1.438514
2015-01-12    0.505498
2015-01-13    0.598026
2015-01-14   -0.302325
2015-01-15   -1.303534
2015-01-16   -0.103629
2015-01-19    1.742230
2015-01-20    0.290905
2015-01-21    1.218446
2015-01-22    1.015890
2015-01-23    0.542587
2015-01-26    0.776732
2015-01-27   -0.174115
2015-01-28   -1.301736
2015-01-29   -1.323173
2015-01-30    0.263355
2015-02-02   -0.261502
2015-02-03    1.524815
2015-02-04    0.506823
2015-02-05   -0.946001
2015-02-06   -0.332047
2015-02-09    0.255062
2015-02-10   -0.975856
2015-02-11    1.369442
                ...
2015-11-20    0.084418
2015-11-23    0.959119
2015-11-24    1.182177
2015-11-25    0.468082
2015-11-26   -0.417394
2015-11-27    2.026357
2015-11-30   -1.509886
2015-12-01   -1.027228
2015-12-02    0.566283
2015-12-03   -1.646841
2015-12-04    1.080723
2015-12-07    0.110060
2015-12-08   -0.128356
2015-12-09    0.447872
2015-12-10    0.360030
2015-12-11   -0.424516
2015-12-14   -0.293016
2015-12-15    0.740425
2015-12-16    0.943533
2015-12-17    0.117263
2015-12-18   -0.827806
2015-12-21    0.850453
2015-12-22   -0.542825
2015-12-23   -0.495759
2015-12-24    0.173302
2015-12-25    0.992894
2015-12-28    0.638668
2015-12-29    1.065088
2015-12-30   -2.189960
2015-12-31   -0.139668
Freq: B, Length: 261, dtype: float64

In [4]:
# Find the sum of the values in s for every Wednesday
# Form a series with weekdays and the random values.
sdays=pd.Series(s.values,index=dtindx.day_name())
print('Series of weekdays and random numbers: ')
print(sdays)

# Get the sum of random numbers for all Wednesdays
print('Sum of random numbers for all Wednesdays in the series: ', sdays.loc['Wednesday'].sum())

Series of weekdays and random numbers:
Thursday     0.877428
Friday      -0.667328
Monday       0.951652
Tuesday      0.425459
Wednesday    0.574672
Thursday     0.252167
Friday       1.438514
Monday       0.505498
Tuesday      0.598026
Wednesday   -0.302325
Thursday    -1.303534
Friday      -0.103629
Monday       1.742230
Tuesday      0.290905
Wednesday    1.218446
Thursday     1.015890
Friday       0.542587
Monday       0.776732
Tuesday     -0.174115
Wednesday   -1.301736
Thursday    -1.323173
Friday       0.263355
Monday      -0.261502
Tuesday      1.524815
Wednesday    0.506823
Thursday    -0.946001
Friday      -0.332047
Monday       0.255062
Tuesday     -0.975856
Wednesday    1.369442
               ...
Friday       0.084418
Monday       0.959119
Tuesday      1.182177
Wednesday    0.468082
Thursday    -0.417394
Friday       2.026357
Monday      -1.509886
Tuesday     -1.027228
Wednesday    0.566283
Thursday    -1.646841
Friday       1.080723
Monday       0.110060
Tuesday     -0.128356
Wednesday    0.447872
Thursday     0.360030
Friday      -0.424516
Monday      -0.293016
Tuesday      0.740425
Wednesday    0.943533
Thursday     0.117263
Friday      -0.827806
Monday       0.850453
Tuesday     -0.542825
Wednesday   -0.495759
Thursday     0.173302
Friday       0.992894
Monday       0.638668
Tuesday      1.065088
Wednesday   -2.189960
Thursday    -0.139668
Length: 261, dtype: float64
Sum of random numbers for all Wednesdays in the series:  -3.554554880299792

In [5]:
# Average For each calendar month
print('Average for each calendar month:')
print(s.groupby(dtindx.month).mean())

Average for each calendar month:
1     0.286260
2     0.285229
3    -0.052312
4    -0.240251
5     0.180909
6     0.127513
7    -0.187303
8    -0.354370
9    -0.065007
10    0.065725
11   -0.003520
12    0.016114
dtype: float64

In [6]:
# For each group of four consecutive calendar months in s, find the date on which the highest value occurred.
# Find the maximum value for a month and form a series. 

scal_mon=pd.Series(s.groupby(dtindx.month).max().values,index=s.groupby(dtindx.month).idxmax())
print(scal_mon)

# Find the highest for every 4 consecutive months. 
# Form windows with 4 consecutive months and find the maximum from every window. 
print('Dates for which the highest value occurred in 4 consecutive months:')
for i in range(9):
    highval=scal_mon[i:4+i]
    print(highval.idxmax().date())

2015-01-19    1.742230
2015-02-27    2.588170
2015-03-03    1.313833
2015-04-06    1.493313
2015-05-11    1.549338
2015-06-24    1.715571
2015-07-06    1.692727
2015-08-10    1.288152
2015-09-01    1.564583
2015-10-05    1.439863
2015-11-12    2.640684
2015-12-04    1.080723
dtype: float64
Dates for which the highest value occurred in 4 consecutive months:
2015-02-27
2015-02-27
2015-06-24
2015-06-24
2015-06-24
2015-06-24
2015-07-06
2015-11-12
2015-11-12